package vue;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
	
/**
 *
 * @author DOCTEURWAMBA
 */
public class SuppressionFournisseur extends JDialog {
    
	private JPanel contentPane;
	private JButton jButton1_Supprimer;
	private JButton jButton2_Annuler;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;  
	private JFrame detailClient0;
    /**
     * Creates new form SupprimerClient
     * @param detailClient 
     */
    public SuppressionFournisseur(String[] values, JFrame detailClient) {
        initComponents(values, detailClient);//,newClient
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                              
    private void initComponents(String[] values, JFrame detailClient) {//, DetailClient newClient

    	contentPane = new JPanel();
    	detailClient0 = detailClient;
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(new Color(199, 21, 133));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setForeground(new Color(199, 21, 133));
        jButton1_Supprimer = new javax.swing.JButton();
        jButton1_Supprimer.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		detailClient0.dispose();
        		dispose();
        	}
        });
        
        jButton2_Annuler = new javax.swing.JButton();
        jButton2_Annuler.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		detailClient0.setEnabled(true);
        		dispose();
        	}
        });
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setTitle("Supprimer client");
        setContentPane(contentPane);
        contentPane.setBackground(new Color(255, 255, 255));
        setBounds(500,200, 575, 641);
        setResizable(false);

        jLabel1.setFont(new Font("Cambria", Font.BOLD, 18)); // NOI18N
        jLabel1.setText("Voulez vous vraiment supprimer le client ");

        String jLabel2Text = values[0]+" "+values[1]+" ?";
        jLabel2.setFont(new Font("Cambria", Font.BOLD, 18)); // NOI18N
        jLabel2.setText(jLabel2Text);

        jButton1_Supprimer.setText("Supprimer");

        jButton2_Annuler.setText("Annuler");

        jLabel3.setIcon(new javax.swing.ImageIcon("./Photo/attention.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton1_Supprimer)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_Annuler))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12))
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Supprimer)
                    .addComponent(jButton2_Annuler))
                .addContainerGap())
        );

        pack();
    }                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuppressionFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuppressionFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuppressionFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuppressionFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	String[]values = new String[]{"Wamba","Alexandra"};
            	JFrame detailClient = new JFrame();
                new SuppressionFournisseur(values, detailClient).setVisible(true);
            }
        });
    }

                 
}

